-- MySQL Script generated by MySQL Workbench
-- Sun Sep  1 15:46:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`summoners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`summoners` (
  `summoner_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `encryptedId` VARCHAR(80) NOT NULL,
  `accountId` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`summoner_id`),
  UNIQUE INDEX `summoner_id_UNIQUE` (`summoner_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `accountId_UNIQUE` (`accountId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`champions` (
  `champion_id` INT NOT NULL,
  `version` VARCHAR(45) NULL,
  `key` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `attack` INT NULL,
  `defense` INT NULL,
  `magic` INT NULL,
  `difficulty` INT NULL,
  PRIMARY KEY (`champion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`champRoles` (
  `role_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champions_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`champions_roles` (
  `champion_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `champion_Roles_champion_id_idx` (`champion_id` ASC) VISIBLE,
  INDEX `champions_roles_role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `champions_roles_champion_id`
    FOREIGN KEY (`champion_id`)
    REFERENCES `mydb`.`champions` (`champion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `champions_roles_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`champRoles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `game_id` INT NOT NULL,
  `season` INT NOT NULL,
  `patch` VARCHAR(45) NULL,
  `region` VARCHAR(45) NOT NULL,
  `gameMode` VARCHAR(45) NOT NULL,
  `mapId` INT NOT NULL,
  `gameType` VARCHAR(45) NOT NULL,
  `gameDuration` INT NOT NULL,
  `gameCreation` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  UNIQUE INDEX `game_id_UNIQUE` (`game_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games_participants` (
  `game_id` INT NOT NULL,
  `summoner_account_id` VARCHAR(80) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `patch` INT NOT NULL,
  `gameMode` VARCHAR(45) NOT NULL,
  `map` VARCHAR(45) NOT NULL,
  `team` INT NOT NULL,
  `champion_id` INT NOT NULL,
  INDEX `games_participants_game_id_idx` (`game_id` ASC) VISIBLE,
  INDEX `games_participants_summoner_account_id_idx` (`summoner_account_id` ASC) VISIBLE,
  INDEX `games_participants_champion_id_idx` (`champion_id` ASC) VISIBLE,
  CONSTRAINT `games_participants_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `games_participants_summoner_account_id`
    FOREIGN KEY (`summoner_account_id`)
    REFERENCES `mydb`.`summoners` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `games_participants_champion_id`
    FOREIGN KEY (`champion_id`)
    REFERENCES `mydb`.`champions` (`champion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_participant_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_participant_stats` (
  `game_id` INT NOT NULL,
  `game_participant_id` VARCHAR(80) NOT NULL,
  `firstBloodAsist` VARCHAR(45) NOT NULL,
  `visionScore` INT NOT NULL,
  `magicDamageDealtToChampions` INT NOT NULL,
  `damageDealtToObjectives` INT NOT NULL,
  `totalTimeCrowdControlDealt` INT NOT NULL,
  `longestTimeSpentLiving` INT NOT NULL,
  `tripleKills` INT NOT NULL,
  `kills` INT NOT NULL,
  `totalScoreRank` INT NOT NULL,
  `neutralMinionsKilled` INT NOT NULL,
  `damageDealtToTurrets` INT NOT NULL,
  `physicalDamageDealtToChampions` INT NOT NULL,
  `largestMultiKill` INT NOT NULL,
  `totalUnitsHealed` INT NOT NULL,
  `wardsKilled` INT NOT NULL,
  `largestCriticalStrike` INT NOT NULL,
  `largestKillingSpree` INT NOT NULL,
  `quadraKills` INT NOT NULL,
  `teamObjective` INT NOT NULL,
  `magicDamageDealt` INT NOT NULL,
  `item2` INT NOT NULL,
  `item3` INT NOT NULL,
  `item0` INT NOT NULL,
  `neutralMinionsKilledTeamJungle` INT NOT NULL,
  `item6` INT NOT NULL,
  `item4` INT NOT NULL,
  `item5` INT NOT NULL,
  `damageSelfMitigated` INT NOT NULL,
  `magicalDamageTaken` INT NOT NULL,
  `firstInhibitorKill` VARCHAR(45) NOT NULL,
  `trueDamageTaken` INT NOT NULL,
  `assists` INT NOT NULL,
  `combatPlayerScore` INT NOT NULL,
  `goldSpent` INT NOT NULL,
  `trueDamageDealt` INT NOT NULL,
  `totalDamageTaken` INT NOT NULL,
  `physicalDamageDealt` INT NOT NULL,
  `sightWardsBoughtInGame` INT NOT NULL,
  `totalDamageDealtToChampions` INT NOT NULL,
  `physicalDamageTaken` INT NOT NULL,
  `totalPlayerScore` INT NOT NULL,
  `win` VARCHAR(45) NOT NULL,
  `objectivePlayerScore` INT NOT NULL,
  `totalDamageDealt` INT NOT NULL,
  `item1` INT NOT NULL,
  `neutralMinionsKilledEnemyJungle` INT NOT NULL,
  `deaths` INT NOT NULL,
  `wardsPlaced` INT NOT NULL,
  `turretKills` INT NOT NULL,
  `firstBloodKill` VARCHAR(45) NOT NULL,
  `trueDamageDealtToChampions` INT NOT NULL,
  `goldEarned` INT NOT NULL,
  `killingSprees` INT NOT NULL,
  `unrealKills` INT NOT NULL,
  `altarsCaptured` INT NOT NULL,
  `firstTowerAssist` VARCHAR(45) NOT NULL,
  `firstTowerKill` VARCHAR(45) NOT NULL,
  `champLevel` INT NOT NULL,
  `doubleKills` INT NOT NULL,
  `inhibitorKills` INT NOT NULL,
  `firstInhibitorAssist` VARCHAR(45) NOT NULL,
  `visionWardsBoughtInGame` INT NOT NULL,
  `altarsNeutralized` INT NOT NULL,
  `pentaKills` INT NOT NULL,
  `totalHeal` INT NOT NULL,
  `totalMinionsKilled` INT NOT NULL,
  `timeCCingOthers` INT NOT NULL,
  INDEX `game_participant_stats_game_participant_id_idx` (`game_participant_id` ASC) VISIBLE,
  CONSTRAINT `game_participant_stats_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game_participant_stats_game_participant_id`
    FOREIGN KEY (`game_participant_id`)
    REFERENCES `mydb`.`games_participants` (`summoner_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teams_stats` (
  `game_id` INT NOT NULL,
  `teamId` INT NOT NULL,
  `firstDragon` VARCHAR(45) NOT NULL,
  `firstInhibitor` VARCHAR(45) NOT NULL,
  `baronKills` INT NOT NULL,
  `firstRiftHerald` VARCHAR(45) NOT NULL,
  `firstBaron` VARCHAR(45) NOT NULL,
  `riftHeraldKills` INT NOT NULL,
  `firstBlood` VARCHAR(45) NOT NULL,
  `vilemawKills` INT NOT NULL,
  `inhibitorKills` INT NOT NULL,
  `firstTower` VARCHAR(45) NOT NULL,
  `towerKills` INT NOT NULL,
  `dominionVictoryScore` INT NOT NULL,
  `win` VARCHAR(45) NOT NULL,
  `dragonKills` INT NOT NULL,
  INDEX `teams_stats_game_id_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `teams_stats_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team_bans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team_bans` (
  `game_id` INT NOT NULL,
  `teamId` INT NOT NULL,
  `pickTurn` INT NOT NULL,
  `championId` INT NOT NULL,
  INDEX `team_bans_game_id_idx` (`game_id` ASC) VISIBLE,
  INDEX `team_bans_champion_id_idx` (`championId` ASC) VISIBLE,
  CONSTRAINT `team_bans_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team_bans_champion_id`
    FOREIGN KEY (`championId`)
    REFERENCES `mydb`.`champions` (`champion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
